import { AccessoryCategory, AccessoryItem } from '../types';

export const ACCESSORY_CATEGORIES: AccessoryCategory[] = [
  { id: 'all', name: 'All Categories', count: 32 },
  { id: 'chargers', name: 'Chargers & Docks', count: 8 },
  { id: 'cables', name: 'USB Cables', count: 6 },
  { id: 'audio', name: 'Wireless Earbuds', count: 9 },
  { id: 'watches', name: 'Smart Watches', count: 5 },
  { id: 'powerbanks', name: 'Power Banks', count: 7 },
  { id: 'speakers', name: 'Bluetooth Speakers', count: 4 },
  { id: 'cases', name: 'Mobile Cases', count: 14 },
  { id: 'protection', name: 'Screen Protectors', count: 12 },
  { id: 'stands', name: 'Mobile Stands & Mounts', count: 6 },
  { id: 'carchargers', name: 'Car Chargers', count: 4 },
  { id: 'gadgets', name: 'Other Gadgets', count: 8 },
];

export const FEATURED_ACCESSORIES: AccessoryItem[] = [
  {
    id: 'magsafe-power-bank',
    name: 'MagSafe Power Bank',
    category: 'powerbanks',
    description: 'Compact wireless charging solution with snap-on magnetic lock, 15W Qi2 output, and brushed alloy trim.',
    price: '₹2,899',
    image: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?q=80&w=800&auto=format&fit=crop',
    rating: 4.9,
    features: ['10,000 mAh Capacity', '15W Fast Magnetic Lock', 'Bi-directional Type-C PD'],
    inStock: true,
  },
  {
    id: 'wireless-earbuds-pro',
    name: 'Wireless Earbuds Pro',
    category: 'audio',
    description: 'Clear sound with premium design. Adaptive active noise cancellation, custom graphene drivers, and 38-hour playback.',
    price: '₹4,499',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=800&auto=format&fit=crop',
    rating: 4.95,
    features: ['-48dB Hybrid ANC', 'Spatial Audio with Head Tracking', 'IPX5 Water Resistant'],
    inStock: true,
  },
  {
    id: 'fast-usbc-charger',
    name: 'Fast USB-C Charger (67W GaN)',
    category: 'chargers',
    description: 'Fast and reliable charging powered by Gallium Nitride (GaN III). Charges laptops, tablets, and smartphones simultaneously.',
    price: '₹1,999',
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?q=80&w=800&auto=format&fit=crop',
    rating: 4.85,
    features: ['67W Max GaN III Tech', 'Dual USB-C + USB-A', 'Active Temperature Shield'],
    inStock: true,
  },
  {
    id: 'smart-watch-series-x',
    name: 'Smart Watch Series X',
    category: 'watches',
    description: 'Stay connected throughout the day with a sapphire crystal display, ECG + SpO2 tracking, and 14-day battery life.',
    price: '₹6,999',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=800&auto=format&fit=crop',
    rating: 4.9,
    features: ['1.43" AMOLED 60Hz', 'Dual-Frequency GPS', 'Titanium Case Finish'],
    inStock: true,
  },
  {
    id: 'premium-phone-case',
    name: 'Premium Phone Case',
    category: 'cases',
    description: 'Protection with a refined finish. Top-grain vegan leather with anodized aluminum camera bezel and microfibre interior.',
    price: '₹1,299',
    image: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?q=80&w=800&auto=format&fit=crop',
    rating: 4.8,
    features: ['10ft Drop Certified', 'MagSafe Array Built-in', 'Tactile Metal Buttons'],
    inStock: true,
  },
  {
    id: 'bluetooth-speaker-mini',
    name: 'Bluetooth Speaker Mini',
    category: 'speakers',
    description: 'Portable entertainment anywhere. 360-degree acoustic acoustic chamber with deep bass resonator and IP67 waterproof build.',
    price: '₹3,499',
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?q=80&w=800&auto=format&fit=crop',
    rating: 4.85,
    features: ['16W Room-filling Bass', '14 Hours Playtime', 'TWS Stereo Pairing'],
    inStock: true,
  },
];
