import { BrandItem } from '../types';

export const BRANDS: BrandItem[] = [
  {
    id: 'apple',
    name: 'Apple',
    tagline: 'iPhone 15 & 16 Series, iPads & Watches',
    logoUrl: '',
    monogram: 'AAPL',
    popularModels: ['iPhone 16 Pro Max', 'iPhone 15', 'Watch Ultra 2'],
  },
  {
    id: 'samsung',
    name: 'Samsung',
    tagline: 'Galaxy S Series, Z Fold & Flip Flagships',
    logoUrl: '',
    monogram: 'SMSG',
    popularModels: ['Galaxy S24 Ultra', 'Galaxy Z Fold6', 'Galaxy A55'],
  },
  {
    id: 'oneplus',
    name: 'OnePlus',
    tagline: 'Never Settle — Flagship Speed & Warp Charge',
    logoUrl: '',
    monogram: '1+',
    popularModels: ['OnePlus 12', 'OnePlus 12R', 'OnePlus Nord 4'],
  },
  {
    id: 'google-pixel',
    name: 'Google Pixel',
    tagline: 'Engineered by Google, Powered by Gemini AI',
    logoUrl: '',
    monogram: 'G',
    popularModels: ['Pixel 9 Pro XL', 'Pixel 9', 'Pixel 8a'],
  },
  {
    id: 'xiaomi',
    name: 'Xiaomi',
    tagline: 'Leica Optics & Flagship Snapdragon Engines',
    logoUrl: '',
    monogram: 'MI',
    popularModels: ['Xiaomi 14 Ultra', 'Xiaomi 14', 'Pad 6'],
  },
  {
    id: 'redmi',
    name: 'Redmi',
    tagline: 'Peak Value, 200MP Cameras & Turbo Speed',
    logoUrl: '',
    monogram: 'RDM',
    popularModels: ['Redmi Note 13 Pro+', 'Redmi 13 5G', 'K70'],
  },
  {
    id: 'realme',
    name: 'Realme',
    tagline: 'Dare to Leap — Ultra-fast Charge & Sony Sensors',
    logoUrl: '',
    monogram: 'R',
    popularModels: ['Realme GT 6', 'Realme 13 Pro+', 'Narzo 70'],
  },
  {
    id: 'vivo',
    name: 'Vivo',
    tagline: 'ZEISS Professional Portrait Imaging',
    logoUrl: '',
    monogram: 'V',
    popularModels: ['Vivo X100 Pro', 'Vivo V40 Pro', 'T3 Ultra'],
  },
  {
    id: 'oppo',
    name: 'OPPO',
    tagline: 'Hasselblad Portrait & SuperVOOC Mastery',
    logoUrl: '',
    monogram: 'O',
    popularModels: ['Find X7 Ultra', 'Reno 12 Pro', 'F27 Pro+'],
  },
  {
    id: 'motorola',
    name: 'Motorola',
    tagline: 'Edge Perfection & Ultra Pantone Finishes',
    logoUrl: '',
    monogram: 'M',
    popularModels: ['Edge 50 Ultra', 'Razr 50 Ultra', 'G85 5G'],
  },
  {
    id: 'nothing',
    name: 'Nothing',
    tagline: 'Glyph Interface & Pure Minimalist OS',
    logoUrl: '',
    monogram: '(N)',
    popularModels: ['Phone (2)', 'Phone (2a) Plus', 'CMF Phone 1'],
  },
  {
    id: 'nokia',
    name: 'Nokia',
    tagline: 'Iconic Durability & Pure Clean Android',
    logoUrl: '',
    monogram: 'NOK',
    popularModels: ['Nokia XR21', 'Nokia G42 5G', 'Classic Series'],
  },
];
