import { SmartphoneProduct } from '../types';

export const PRODUCTS: SmartphoneProduct[] = [
  {
    id: 'iphone-17-pro',
    brand: 'Apple',
    name: 'iPhone 17 Pro',
    description: 'Precision forged in aerospace titanium with next-generation neural architecture and studio camera telemetry.',
    badge: 'Flagship Edition',
    price: '₹1,34,900',
    originalPrice: '₹1,39,900',
    image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?q=80&w=800&auto=format&fit=crop',
    specs: {
      display: '6.3" Super Retina XDR 120Hz ProMotion',
      processor: 'A19 Pro Bionic with Neural Accelerators',
      camera: 'Triple 48MP Fusion Studio Array + 5x Prism',
      battery: 'Up to 29 hrs video playback, 35W MagSafe',
      storage: '256GB / 512GB / 1TB NVMe',
    },
    colors: [
      { name: 'Natural Titanium', hex: '#9E9A93' },
      { name: 'Deep Crimson', hex: '#4A080E' },
      { name: 'Space Black', hex: '#1C1C1E' },
      { name: 'Desert Sand', hex: '#C2B8A3' },
    ],
    storageOptions: ['256GB', '512GB', '1TB'],
  },
  {
    id: 'samsung-galaxy-s26-ultra',
    brand: 'Samsung',
    name: 'Galaxy S26 Ultra',
    description: 'The definitive productivity beast with integrated S-Pen, 200MP Quad Telephoto and Galaxy AI intelligence.',
    badge: 'Pro Creator',
    price: '₹1,29,999',
    originalPrice: '₹1,34,999',
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?q=80&w=800&auto=format&fit=crop',
    specs: {
      display: '6.8" Dynamic AMOLED 2X QHD+ 2600 nits',
      processor: 'Snapdragon 8 Elite Mobile Platform',
      camera: '200MP Main + 50MP 5x + 10MP 3x + 12MP UW',
      battery: '5,000 mAh with 45W Super Fast 2.0',
      storage: '256GB / 512GB / 1TB UFS 4.0',
    },
    colors: [
      { name: 'Titanium Gray', hex: '#636569' },
      { name: 'Burgundy Shadow', hex: '#58111A' },
      { name: 'Obsidian Black', hex: '#171717' },
      { name: 'Amber Gold', hex: '#D6C5A0' },
    ],
    storageOptions: ['256GB', '512GB', '1TB'],
  },
  {
    id: 'oneplus-14',
    brand: 'OnePlus',
    name: 'OnePlus 14',
    description: 'Engineered for untamed speed. 4th Gen Hasselblad camera calibration and 100W SUPERVOOC hyper-charge.',
    badge: 'Ultra Performance',
    price: '₹64,999',
    originalPrice: '₹69,999',
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?q=80&w=800&auto=format&fit=crop',
    specs: {
      display: '6.82" 2K 120Hz ProXDR with Aqua Touch',
      processor: 'Snapdragon 8 Elite with Dual Cryo-Velocity VC',
      camera: '50MP Sony LYT-808 + 64MP 3x Periscope',
      battery: '5,400 mAh with 100W Wired + 50W Wireless',
      storage: '256GB / 512GB LPDDR5X',
    },
    colors: [
      { name: 'Silky Black', hex: '#1E1E20' },
      { name: 'Flowy Emerald', hex: '#2A4736' },
      { name: 'Champagne Silver', hex: '#DCD4BE' },
    ],
    storageOptions: ['256GB', '512GB'],
  },
  {
    id: 'google-pixel-10-pro',
    brand: 'Google Pixel',
    name: 'Pixel 10 Pro',
    description: 'Built from the silicon up for Gemini Nano. Computational photography that captures reality with pristine depth.',
    badge: 'Gemini AI Core',
    price: '₹1,09,999',
    originalPrice: '₹1,14,999',
    image: 'https://images.unsplash.com/photo-1598327105854-c8674faddf79?q=80&w=800&auto=format&fit=crop',
    specs: {
      display: '6.7" Super Actua OLED (1-120Hz, 3000 nits)',
      processor: 'Google Tensor G5 with Titan M2 security',
      camera: '50MP Octa PD + 48MP Quad PD Tele + 48MP UW',
      battery: '5,060 mAh with 30W Fast Charge',
      storage: '128GB / 256GB / 512GB NVMe',
    },
    colors: [
      { name: 'Obsidian', hex: '#1B1B1C' },
      { name: 'Porcelain', hex: '#F0EEE8' },
      { name: 'Hazel Stone', hex: '#585952' },
      { name: 'Rose Quartz', hex: '#D8B8B5' },
    ],
    storageOptions: ['128GB', '256GB', '512GB'],
  },
  {
    id: 'xiaomi-16-pro',
    brand: 'Xiaomi',
    name: 'Xiaomi 16 Pro',
    description: 'Leica Summilux master optics paired with ultra-dense battery materials and titanium architectural alloy.',
    badge: 'Leica Optics',
    price: '₹79,999',
    originalPrice: '₹84,999',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?q=80&w=800&auto=format&fit=crop',
    specs: {
      display: '6.73" WQHD+ AMOLED with DC dimming',
      processor: 'Snapdragon 8 Elite with IceLoop Cooling',
      camera: '50MP 1-inch Light Fusion 900 + Leica 75mm Floating',
      battery: '4,880 mAh with 120W HyperCharge',
      storage: '256GB / 512GB UFS 4.0',
    },
    colors: [
      { name: 'Titanium Black', hex: '#232324' },
      { name: 'Jade White', hex: '#EDE8DD' },
      { name: 'Leica Silver', hex: '#BDBBB6' },
    ],
    storageOptions: ['256GB', '512GB'],
  },
  {
    id: 'nothing-phone',
    brand: 'Nothing',
    name: 'Nothing Phone',
    description: 'Translucent craftsmanship illuminated by the interactive Glyph Interface. Pure Nothing OS, zero bloatware.',
    badge: 'Iconic Minimalist',
    price: '₹39,999',
    originalPrice: '₹44,999',
    image: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?q=80&w=800&auto=format&fit=crop',
    specs: {
      display: '6.7" Flexible LTPO OLED (1-120Hz HDR10+)',
      processor: 'Snapdragon Flagship Series with Custom Heatsink',
      camera: 'Dual 50MP Sony Sensor with OIS & EIS',
      battery: '4,700 mAh with 45W PPS Fast Charge',
      storage: '128GB / 256GB / 512GB',
    },
    colors: [
      { name: 'Dark Smoke', hex: '#1E1E22' },
      { name: 'Pure White', hex: '#F3F2EF' },
    ],
    storageOptions: ['128GB', '256GB', '512GB'],
  },
];
