import { RepairServiceItem, RepairStep } from '../types';

export const REPAIR_SERVICES: RepairServiceItem[] = [
  {
    id: 'display-replacement',
    name: 'Display Replacement',
    description: 'Cracked or damaged display replacement using certified OEM-grade OLED and AMOLED panels with touch calibration.',
    iconName: 'Smartphone',
    turnaround: '30 - 45 mins',
    warranty: '180 Days Warranty',
    startingPrice: '₹1,899',
    popularFor: 'OLED / Super Retina / Dynamic AMOLED',
  },
  {
    id: 'battery-replacement',
    name: 'Battery Replacement',
    description: 'Restore all-day battery performance with high-cycle capacity cells, zero thermal degradation, and cycle reset.',
    iconName: 'BatteryCharging',
    turnaround: '25 - 40 mins',
    warranty: '180 Days Warranty',
    startingPrice: '₹1,299',
    popularFor: 'High capacity cells with health telemetry',
  },
  {
    id: 'charging-port-repair',
    name: 'Charging Port Repair',
    description: 'Fix loose charging pins, slow power delivery, intermittent connections, and Type-C / Lightning port debris.',
    iconName: 'Zap',
    turnaround: '20 - 30 mins',
    warranty: '90 Days Warranty',
    startingPrice: '₹799',
    popularFor: 'Fast charging & OTG data recovery',
  },
  {
    id: 'camera-repair',
    name: 'Camera Repair',
    description: 'Repair blurred focus motors, cracked sapphire lens protectors, sensor jitter, and broken aperture rings.',
    iconName: 'Camera',
    turnaround: '45 - 60 mins',
    warranty: '90 Days Warranty',
    startingPrice: '₹1,499',
    popularFor: 'OIS stabilization & ultrawide modules',
  },
  {
    id: 'speaker-microphone',
    name: 'Speaker & Microphone',
    description: 'Restore crisp spatial audio, clear call acoustics, stereo speaker channels, and noise-canceling mic arrays.',
    iconName: 'Volume2',
    turnaround: '30 mins',
    warranty: '90 Days Warranty',
    startingPrice: '₹699',
    popularFor: 'Earpiece grille & loudspeaker drivers',
  },
  {
    id: 'software-service',
    name: 'Software Service',
    description: 'Bootloop recovery, OS updates, factory reset loops, data migration, carrier unlocking, and malware cleansing.',
    iconName: 'Cpu',
    turnaround: '30 - 60 mins',
    warranty: '30 Days Warranty',
    startingPrice: '₹499',
    popularFor: 'iOS, One UI, OxygenOS, HyperOS, Android',
  },
  {
    id: 'water-damage',
    name: 'Water Damage',
    description: 'Deep ultrasonic PCB cleaning, electrolytic corrosion removal, component reballing, and safe data salvaging.',
    iconName: 'Droplets',
    turnaround: '2 - 4 hours',
    warranty: 'Diagnostic Verified',
    startingPrice: '₹1,199',
    popularFor: 'Liquid ingress & moisture warning reset',
  },
  {
    id: 'general-service',
    name: 'General Service',
    description: 'Complete 32-point mobile diagnostic scan, thermal paste renewal, dust purge, and hardware health certification.',
    iconName: 'Wrench',
    turnaround: '30 mins',
    warranty: 'Full Health Report',
    startingPrice: '₹399',
    popularFor: 'Preventative care & pre-sale inspection',
  },
];

export const REPAIR_STEPS: RepairStep[] = [
  {
    step: '01',
    title: 'Diagnose',
    description: 'We inspect the device.',
    detail: 'Precision optical and digital diagnostics to pinpoint the exact component fault in minutes.',
  },
  {
    step: '02',
    title: 'Estimate',
    description: 'We explain the repair and cost.',
    detail: 'Complete transparency with upfront part pricing, labor warranty, and zero hidden charges.',
  },
  {
    step: '03',
    title: 'Repair',
    description: 'Our technicians work on the device.',
    detail: 'Conducted in ESD-safe clean stations using precision microscopic tools and genuine-spec parts.',
  },
  {
    step: '04',
    title: 'Deliver',
    description: 'Your phone is ready to go.',
    detail: 'Post-service 15-point quality check, warranty badge issued, and hand-delivered pristine to you.',
  },
];
